apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: argocd
type: Opaque
data:
  # Format: username:password (base64 encoded)
  # Eg: echo -n "username:password" | base64
  # Token permissions: read:packages
  creds: SWduYUxvZzpnaHBfSkNWeWl0RmJvdW1ISzVwMzdrenlPOGJsU05YWUxQMGpuckt2